import "dotenv/config";

export const $config = {
  KEYCLOAK_ENDPOINT_BASE: process.env.KEYCLOAK_ENDPOINT_BASE!,
  KEYCLOAK_MASTER_CLIENT_ID: process.env.KEYCLOAK_MASTER_CLIENT_ID!,
  KEYCLOAK_MASTER_USER: process.env.KEYCLOAK_MASTER_USER!,
  KEYCLOAK_MASTER_PASSWORD: process.env.KEYCLOAK_MASTER_PASSWORD!,
  KEYCLOAK_MASTER_GRANT_TYPE: process.env.KEYCLOAK_MASTER_GRANT_TYPE!,
  KEYCLOAK_MASTER_SECRET_KEY: process.env.KEYCLOAK_MASTER_SECRET_KEY!,
};
